---
- hosts: node-1
  become: yes
  tasks:
# Installing httpd
  - name: Install httpd 
    yum:
        name: httpd
        state: present
# starting httpd
  - name: start httpd 
    service:
        name: httpd
        state: restarted
# Enabling httpd 
  - name: Enabled httpd 
    service:
        name: httpd
        enabled: yes

  - name: Index file copying
    copy:
      src: ./index.html
      dest: /var/www/html/
      owner: apache
      group: apache
      mode: 0644
 